# Hexo Configuration
## Docs: https://hexo.io/docs/
## Source: https://github.com/hexojs/hexo

# Site
title: mypUI
subtitle:
description: "基于uniapp快速开发nvue页面的组件库与工具集"
author: Yuping Ma
email:
language: zh-CN

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://mypui.asnowsoft.cn
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code

# Directory
source_dir: src
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
highlight:
  enable: true
  line_number: false
  tab_replace:
  hljs: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 0
category: 0
tag: 0

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname:

# Include/Exclude Files/Folders
exclude:
## Exclude example code from Nunjucks
  - "v2/examples/vue-20-*/*"

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: vue
exclude_generator:

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# Offline
## Config passed to sw-precache
## https://github.com/JLHwung/hexo-offline
offline:
  maximumFileSizeToCacheInBytes: 10485760
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,jpeg,gif,svg,eot,ttf,woff,woff2,json,xml}
  stripPrefix: public
  verbose: true
  runtimeCaching:
    # Ad Sources - should be networkFirst
    - urlPattern: /*
      handler: networkFirst
      options:
        origin: sendgrid.sp1.convertro.com
    - urlPattern: /*
      handler: networkFirst
      options:
        origin: ad.doubleclick.net
    # CDNs - should be cacheFirst, since they should be used specific versions so should not change
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.jsdelivr.net
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: fonts.googleapis.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: fonts.gstatic.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdnjs.cloudflare.com
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: maxcdn.bootstrapcdn.com

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:wakaryry/mypui-doc.git
  branch: h-pages

feed:
  type: atom
  path: atom.xml
  limit: 20

alias:
  
